import groovy.json.*

def jsonData = '''
[
    {
        "contractual_eta_dlv": null,
        "contractual_eta_pod": null,
        "contractual_etd_pol": null,
        "created": "2025-10-10T14:48+0000",
        "descriptive_name": null,
        "id": 110234282,
        "last_actuals_update": null,
        "last_carrier_update": null,
        "modified": "2025-10-10T16:03+0000",
        "on_hold": false,
        "owner_internal_id": null,
        "request_carrier_name": "test",
        "request_key": "MAEU721037207",
        "request_type": "m_bl",
        "status": 3,
        "status_verbose": "new",
        "suspicious_key": false,
        "master_shipment_id": "ccbba602-d1b4-5e65-942b-7664f5b8f19e",
        "master_shipment_leg_id": "ff1cf005-6b6d-5348-98a1-c1ec40306501",
        "account_id": 4913,
        "account_name": "Shanghai inbound",
        "tags": [],
        "internal_tags": [],
        "url": "https://capi.ocean-insights.com/containertracking/v2/subscriptions/110234282/",
        "containershipments": [],
        "subscription_status_page_url": "https://ctt.ocean-insights.com/#/subscription/110234282?share=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImQzNzQ3M2FkMWY4YzRjZTg5NDM5YTFkZTVmZTE4Y2U2In0.eyJzdWIiOiJzdWI6MTEwMjM0MjgyIiwibm9uY2UiOiJoNHRVYmg3dzBzNk1GMXE4d0dzQ2ZENEtqT1JzTnVYQjA2eXRXSXZfdWRNIn0.onmrNEmU0Akplmo5R_EA932TS0mW-_dRZN-h5SQ_SQU"
    },
    {
        "contractual_eta_dlv": null,
        "contractual_eta_pod": null,
        "contractual_etd_pol": null,
        "created": "2025-10-01T11:44+0000",
        "descriptive_name": null,
        "id": 110015398,
        "last_actuals_update": "2025-10-16T02:34+0000",
        "last_carrier_update": "2025-10-15T06:21+0000",
        "modified": "2025-10-16T02:34+0000",
        "on_hold": false,
        "owner_internal_id": null,
        "request_carrier_name": "Maersk",
        "request_key": "MAEU721037207",
        "request_type": "m_bl",
        "status": 1,
        "status_verbose": "active",
        "suspicious_key": false,
        "master_shipment_id": "ec5e9163-73bf-599d-9752-5deb7827e924",
        "master_shipment_leg_id": "7a0f19c0-12b6-58ed-837a-4ac8dc1d260b",
        "account_id": 4913,
        "account_name": "Shanghai inbound",
        "tags": [],
        "internal_tags": [],
        "url": "https://capi.ocean-insights.com/containertracking/v2/subscriptions/110015398/",
        "containershipments": [
            {
                "id": 69879366,
                "shipmentsubscription_status": 1,
                "status_verbose": "land transport to Place of Delivery",
                "current_vessel_nextport": null,
                "current_vessel_position": null,
                "current_vessel": null,
                "container_type_iso": "22TN",
                "container_type_str": "20 ft Standard Tank Container",
                "shipmentsubscription_status_verbose": "active",
                "shipmentsubscription_on_hold": false,
                "shipmentsubscription_id": 110015398,
                "lifecycle_status_verbose": "active",
                "tsp4_loc": null,
                "tsp3_loc": null,
                "tsp2_loc": null,
                "tsp1_loc": null,
                "leg5_vessel": null,
                "leg4_vessel": null,
                "leg3_vessel": null,
                "leg2_vessel": null,
                "leg1_vessel": {
                    "name": "VAGA MAERSK",
                    "imo": 9778545,
                    "id": 7457146
                },
                "dlv_loc": null,
                "pod_loc": {
                    "name": "Alexandria (Al Iskandariyh)",
                    "locode": "EGALY",
                    "timezone": "Africa/Cairo",
                    "latitude": 31.166667,
                    "longitude": 29.833333,
                    "city": "Alexandria",
                    "state": "Alexandria",
                    "country": "Egypt",
                    "country_iso2": "EG",
                    "country_iso3": "EGY"
                },
                "pol_loc": {
                    "name": "Antwerp",
                    "locode": "BEANR",
                    "timezone": "Europe/Brussels",
                    "latitude": 51.216667,
                    "longitude": 4.4,
                    "city": "Antwerpen",
                    "state": "Flanders",
                    "country": "Belgium",
                    "country_iso2": "BE",
                    "country_iso3": "BEL"
                },
                "origin_loc": null,
                "carrier_name": "Maersk",
                "carrier_scac": "MAEU",
                "container_number": "SEGU8001620",
                "descriptive_name": null,
                "shipmentsubscription_descriptive_name": null,
                "shipmentsubscription_tags": [],
                "transport_modes_verbose": [
                    "ocean"
                ],
                "transport_modes": [
                    10
                ],
                "url": "https://capi.ocean-insights.com/containertracking/v2/shipments/69879366/",
                "shipmentsubscription": "https://capi.ocean-insights.com/containertracking/v2/subscriptions/110015398/",
                "tags": [],
                "tsp1_vslarrival_prediction": null,
                "tsp2_vslarrival_prediction": null,
                "tsp3_vslarrival_prediction": null,
                "tsp4_vslarrival_prediction": null,
                "pod_vslarrival_prediction": null,
                "pod_discharge_prediction": null,
                "leg1_service": null,
                "leg2_service": null,
                "leg3_service": null,
                "leg4_service": null,
                "leg5_service": null,
                "pod_timeofarrival_warning": null,
                "empty_pickup_loc": null,
                "availability_loc": null,
                "lif_loc": null,
                "empty_return_loc": null,
                "incidents": [],
                "identifiers": [
                    {
                        "type": "b_id",
                        "reference_number": "721037207"
                    }
                ],
                "booking_number": null,
                "bl_number": "MAEU721037207",
                "weight": null,
                "status": 19,
                "lifecycle_status": 0,
                "id_date": "2025-09-15",
                "empty_pickup_planned_initial": null,
                "empty_pickup_planned_last": null,
                "empty_pickup_actual": null,
                "origin_pickup_planned_initial": null,
                "origin_pickup_planned_last": null,
                "origin_pickup_actual": null,
                "pol_arrival_planned_initial": null,
                "pol_arrival_planned_last": null,
                "pol_arrival_actual": "2025-09-15T15:23+0000",
                "pol_loaded_planned_initial": null,
                "pol_loaded_planned_last": null,
                "pol_loaded_actual": "2025-09-19T14:37+0000",
                "pol_vsldeparture_planned_initial": null,
                "pol_vsldeparture_planned_last": null,
                "pol_vsldeparture_actual": "2025-09-19T20:06+0000",
                "pol_vsldeparture_detected": "2025-09-19T20:20+0000",
                "leg1_voyage": "537S",
                "tsp1_vslarrival_planned_initial": null,
                "tsp1_vslarrival_planned_last": null,
                "tsp1_vslarrival_actual": null,
                "tsp1_vslarrival_detected": null,
                "tsp1_discharge_planned_initial": null,
                "tsp1_discharge_planned_last": null,
                "tsp1_discharge_actual": null,
                "tsp1_loaded_planned_initial": null,
                "tsp1_loaded_planned_last": null,
                "tsp1_loaded_actual": null,
                "tsp1_vsldeparture_planned_initial": null,
                "tsp1_vsldeparture_planned_last": null,
                "tsp1_vsldeparture_actual": null,
                "tsp1_vsldeparture_detected": null,
                "leg2_voyage": null,
                "tsp2_vslarrival_planned_initial": null,
                "tsp2_vslarrival_planned_last": null,
                "tsp2_vslarrival_actual": null,
                "tsp2_vslarrival_detected": null,
                "tsp2_discharge_planned_initial": null,
                "tsp2_discharge_planned_last": null,
                "tsp2_discharge_actual": null,
                "tsp2_loaded_planned_initial": null,
                "tsp2_loaded_planned_last": null,
                "tsp2_loaded_actual": null,
                "tsp2_vsldeparture_planned_initial": null,
                "tsp2_vsldeparture_planned_last": null,
                "tsp2_vsldeparture_actual": null,
                "tsp2_vsldeparture_detected": null,
                "leg3_voyage": null,
                "tsp3_vslarrival_planned_initial": null,
                "tsp3_vslarrival_planned_last": null,
                "tsp3_vslarrival_actual": null,
                "tsp3_vslarrival_detected": null,
                "tsp3_discharge_planned_initial": null,
                "tsp3_discharge_planned_last": null,
                "tsp3_discharge_actual": null,
                "tsp3_loaded_planned_initial": null,
                "tsp3_loaded_planned_last": null,
                "tsp3_loaded_actual": null,
                "tsp3_vsldeparture_planned_initial": null,
                "tsp3_vsldeparture_planned_last": null,
                "tsp3_vsldeparture_actual": null,
                "tsp3_vsldeparture_detected": null,
                "leg4_voyage": null,
                "tsp4_vslarrival_planned_initial": null,
                "tsp4_vslarrival_planned_last": null,
                "tsp4_vslarrival_actual": null,
                "tsp4_vslarrival_detected": null,
                "tsp4_discharge_planned_initial": null,
                "tsp4_discharge_planned_last": null,
                "tsp4_discharge_actual": null,
                "tsp4_loaded_planned_initial": null,
                "tsp4_loaded_planned_last": null,
                "tsp4_loaded_actual": null,
                "tsp4_vsldeparture_planned_initial": null,
                "tsp4_vsldeparture_planned_last": null,
                "tsp4_vsldeparture_actual": null,
                "tsp4_vsldeparture_detected": null,
                "leg5_voyage": null,
                "pod_vslarrival_planned_initial": null,
                "pod_vslarrival_planned_last": null,
                "pod_vslarrival_actual": "2025-09-27T18:39+0000",
                "pod_vslarrival_detected": "2025-09-27T18:23+0000",
                "pod_discharge_planned_initial": null,
                "pod_discharge_planned_last": null,
                "pod_discharge_actual": "2025-09-28T10:00+0000",
                "pod_departure_planned_initial": null,
                "pod_departure_planned_last": null,
                "pod_departure_actual": "2025-10-02T10:28+0000",
                "lif_arrival_planned_initial": null,
                "lif_arrival_planned_last": null,
                "lif_arrival_actual": null,
                "lif_departure_planned_initial": null,
                "lif_departure_planned_last": null,
                "lif_departure_actual": null,
                "dlv_delivery_planned_initial": null,
                "dlv_delivery_planned_last": null,
                "dlv_delivery_actual": null,
                "empty_return_planned_initial": null,
                "empty_return_planned_last": null,
                "empty_return_actual": null,
                "empty_return_customer": null,
                "ts_count": 0,
                "customs_release_state": null,
                "customs_release_date": null,
                "carrier_release_state": null,
                "carrier_release_date": null,
                "availability_date": null,
                "created": "2025-10-01T11:47+0000",
                "modified": "2025-10-16T02:34+0000",
                "shipment_status_page_url": "https://ctt.ocean-insights.com/#/shipment/69879366?share=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImQzNzQ3M2FkMWY4YzRjZTg5NDM5YTFkZTVmZTE4Y2U2In0.eyJzdWIiOiJzaHA6Njk4NzkzNjYiLCJub25jZSI6IlRTTjlQLXViY05rSVRZbk9mbFVJLTRLdzNzWkt0V3VRMDhzMnh3aVdjVlkifQ.TgADjx1Nd_GEKJ5HONuuqk3AnxdOe5hIiLT4g7B8XJs"
            },
            {
                "id": 69879367,
                "shipmentsubscription_status": 1,
                "status_verbose": "land transport to Place of Delivery",
                "current_vessel_nextport": null,
                "current_vessel_position": null,
                "current_vessel": null,
                "container_type_iso": "22TN",
                "container_type_str": "20 ft Standard Tank Container",
                "shipmentsubscription_status_verbose": "active",
                "shipmentsubscription_on_hold": false,
                "shipmentsubscription_id": 110015398,
                "lifecycle_status_verbose": "active",
                "tsp4_loc": null,
                "tsp3_loc": null,
                "tsp2_loc": null,
                "tsp1_loc": null,
                "leg5_vessel": null,
                "leg4_vessel": null,
                "leg3_vessel": null,
                "leg2_vessel": null,
                "leg1_vessel": {
                    "name": "VAGA MAERSK",
                    "imo": 9778545,
                    "id": 7457146
                },
                "dlv_loc": null,
                "pod_loc": {
                    "name": "Alexandria (Al Iskandariyh)",
                    "locode": "EGALY",
                    "timezone": "Africa/Cairo",
                    "latitude": 31.166667,
                    "longitude": 29.833333,
                    "city": "Alexandria",
                    "state": "Alexandria",
                    "country": "Egypt",
                    "country_iso2": "EG",
                    "country_iso3": "EGY"
                },
                "pol_loc": {
                    "name": "Antwerp",
                    "locode": "BEANR",
                    "timezone": "Europe/Brussels",
                    "latitude": 51.216667,
                    "longitude": 4.4,
                    "city": "Antwerpen",
                    "state": "Flanders",
                    "country": "Belgium",
                    "country_iso2": "BE",
                    "country_iso3": "BEL"
                },
                "origin_loc": null,
                "carrier_name": "Maersk",
                "carrier_scac": "MAEU",
                "container_number": "TIFU1508181",
                "descriptive_name": null,
                "shipmentsubscription_descriptive_name": null,
                "shipmentsubscription_tags": [],
                "transport_modes_verbose": [
                    "ocean"
                ],
                "transport_modes": [
                    10
                ],
                "url": "https://capi.ocean-insights.com/containertracking/v2/shipments/69879367/",
                "shipmentsubscription": "https://capi.ocean-insights.com/containertracking/v2/subscriptions/110015398/",
                "tags": [],
                "tsp1_vslarrival_prediction": null,
                "tsp2_vslarrival_prediction": null,
                "tsp3_vslarrival_prediction": null,
                "tsp4_vslarrival_prediction": null,
                "pod_vslarrival_prediction": null,
                "pod_discharge_prediction": null,
                "leg1_service": null,
                "leg2_service": null,
                "leg3_service": null,
                "leg4_service": null,
                "leg5_service": null,
                "pod_timeofarrival_warning": null,
                "empty_pickup_loc": null,
                "availability_loc": null,
                "lif_loc": null,
                "empty_return_loc": null,
                "incidents": [],
                "identifiers": [
                    {
                        "type": "b_id",
                        "reference_number": "721037207"
                    }
                ],
                "booking_number": null,
                "bl_number": "MAEU721037207",
                "weight": null,
                "status": 19,
                "lifecycle_status": 0,
                "id_date": "2025-09-15",
                "empty_pickup_planned_initial": null,
                "empty_pickup_planned_last": null,
                "empty_pickup_actual": null,
                "origin_pickup_planned_initial": null,
                "origin_pickup_planned_last": null,
                "origin_pickup_actual": null,
                "pol_arrival_planned_initial": null,
                "pol_arrival_planned_last": null,
                "pol_arrival_actual": "2025-09-15T16:30+0000",
                "pol_loaded_planned_initial": null,
                "pol_loaded_planned_last": null,
                "pol_loaded_actual": "2025-09-19T14:22+0000",
                "pol_vsldeparture_planned_initial": null,
                "pol_vsldeparture_planned_last": null,
                "pol_vsldeparture_actual": "2025-09-19T20:06+0000",
                "pol_vsldeparture_detected": "2025-09-19T20:20+0000",
                "leg1_voyage": "537S",
                "tsp1_vslarrival_planned_initial": null,
                "tsp1_vslarrival_planned_last": null,
                "tsp1_vslarrival_actual": null,
                "tsp1_vslarrival_detected": null,
                "tsp1_discharge_planned_initial": null,
                "tsp1_discharge_planned_last": null,
                "tsp1_discharge_actual": null,
                "tsp1_loaded_planned_initial": null,
                "tsp1_loaded_planned_last": null,
                "tsp1_loaded_actual": null,
                "tsp1_vsldeparture_planned_initial": null,
                "tsp1_vsldeparture_planned_last": null,
                "tsp1_vsldeparture_actual": null,
                "tsp1_vsldeparture_detected": null,
                "leg2_voyage": null,
                "tsp2_vslarrival_planned_initial": null,
                "tsp2_vslarrival_planned_last": null,
                "tsp2_vslarrival_actual": null,
                "tsp2_vslarrival_detected": null,
                "tsp2_discharge_planned_initial": null,
                "tsp2_discharge_planned_last": null,
                "tsp2_discharge_actual": null,
                "tsp2_loaded_planned_initial": null,
                "tsp2_loaded_planned_last": null,
                "tsp2_loaded_actual": null,
                "tsp2_vsldeparture_planned_initial": null,
                "tsp2_vsldeparture_planned_last": null,
                "tsp2_vsldeparture_actual": null,
                "tsp2_vsldeparture_detected": null,
                "leg3_voyage": null,
                "tsp3_vslarrival_planned_initial": null,
                "tsp3_vslarrival_planned_last": null,
                "tsp3_vslarrival_actual": null,
                "tsp3_vslarrival_detected": null,
                "tsp3_discharge_planned_initial": null,
                "tsp3_discharge_planned_last": null,
                "tsp3_discharge_actual": null,
                "tsp3_loaded_planned_initial": null,
                "tsp3_loaded_planned_last": null,
                "tsp3_loaded_actual": null,
                "tsp3_vsldeparture_planned_initial": null,
                "tsp3_vsldeparture_planned_last": null,
                "tsp3_vsldeparture_actual": null,
                "tsp3_vsldeparture_detected": null,
                "leg4_voyage": null,
                "tsp4_vslarrival_planned_initial": null,
                "tsp4_vslarrival_planned_last": null,
                "tsp4_vslarrival_actual": null,
                "tsp4_vslarrival_detected": null,
                "tsp4_discharge_planned_initial": null,
                "tsp4_discharge_planned_last": null,
                "tsp4_discharge_actual": null,
                "tsp4_loaded_planned_initial": null,
                "tsp4_loaded_planned_last": null,
                "tsp4_loaded_actual": null,
                "tsp4_vsldeparture_planned_initial": null,
                "tsp4_vsldeparture_planned_last": null,
                "tsp4_vsldeparture_actual": null,
                "tsp4_vsldeparture_detected": null,
                "leg5_voyage": null,
                "pod_vslarrival_planned_initial": null,
                "pod_vslarrival_planned_last": null,
                "pod_vslarrival_actual": "2025-09-27T18:39+0000",
                "pod_vslarrival_detected": "2025-09-27T18:23+0000",
                "pod_discharge_planned_initial": null,
                "pod_discharge_planned_last": null,
                "pod_discharge_actual": "2025-09-28T10:20+0000",
                "pod_departure_planned_initial": null,
                "pod_departure_planned_last": null,
                "pod_departure_actual": "2025-10-02T10:34+0000",
                "lif_arrival_planned_initial": null,
                "lif_arrival_planned_last": null,
                "lif_arrival_actual": null,
                "lif_departure_planned_initial": null,
                "lif_departure_planned_last": null,
                "lif_departure_actual": null,
                "dlv_delivery_planned_initial": null,
                "dlv_delivery_planned_last": null,
                "dlv_delivery_actual": null,
                "empty_return_planned_initial": null,
                "empty_return_planned_last": null,
                "empty_return_actual": null,
                "empty_return_customer": null,
                "ts_count": 0,
                "customs_release_state": null,
                "customs_release_date": null,
                "carrier_release_state": null,
                "carrier_release_date": null,
                "availability_date": null,
                "created": "2025-10-01T11:47+0000",
                "modified": "2025-10-16T02:34+0000",
                "shipment_status_page_url": "https://ctt.ocean-insights.com/#/shipment/69879367?share=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImQzNzQ3M2FkMWY4YzRjZTg5NDM5YTFkZTVmZTE4Y2U2In0.eyJzdWIiOiJzaHA6Njk4NzkzNjciLCJub25jZSI6Im1KNkV1OUpOcEp2bmYzSWRaS0wzQW5yNnNDclljYXVDejd2eUFnWU5WMnMifQ.xk-kRe2ql2rJaRYcsm4SXrKWlNBc4NTdCayBNg0XAOs"
            },
            {
                "id": 69879368,
                "shipmentsubscription_status": 1,
                "status_verbose": "land transport to Place of Delivery",
                "current_vessel_nextport": null,
                "current_vessel_position": null,
                "current_vessel": null,
                "container_type_iso": "22TN",
                "container_type_str": "20 ft Standard Tank Container",
                "shipmentsubscription_status_verbose": "active",
                "shipmentsubscription_on_hold": false,
                "shipmentsubscription_id": 110015398,
                "lifecycle_status_verbose": "active",
                "tsp4_loc": null,
                "tsp3_loc": null,
                "tsp2_loc": null,
                "tsp1_loc": null,
                "leg5_vessel": null,
                "leg4_vessel": null,
                "leg3_vessel": null,
                "leg2_vessel": null,
                "leg1_vessel": {
                    "name": "VAGA MAERSK",
                    "imo": 9778545,
                    "id": 7457146
                },
                "dlv_loc": null,
                "pod_loc": {
                    "name": "Alexandria (Al Iskandariyh)",
                    "locode": "EGALY",
                    "timezone": "Africa/Cairo",
                    "latitude": 31.166667,
                    "longitude": 29.833333,
                    "city": "Alexandria",
                    "state": "Alexandria",
                    "country": "Egypt",
                    "country_iso2": "EG",
                    "country_iso3": "EGY"
                },
                "pol_loc": {
                    "name": "Antwerp",
                    "locode": "BEANR",
                    "timezone": "Europe/Brussels",
                    "latitude": 51.216667,
                    "longitude": 4.4,
                    "city": "Antwerpen",
                    "state": "Flanders",
                    "country": "Belgium",
                    "country_iso2": "BE",
                    "country_iso3": "BEL"
                },
                "origin_loc": null,
                "carrier_name": "Maersk",
                "carrier_scac": "MAEU",
                "container_number": "GMCU6062760",
                "descriptive_name": null,
                "shipmentsubscription_descriptive_name": null,
                "shipmentsubscription_tags": [],
                "transport_modes_verbose": [
                    "ocean"
                ],
                "transport_modes": [
                    10
                ],
                "url": "https://capi.ocean-insights.com/containertracking/v2/shipments/69879368/",
                "shipmentsubscription": "https://capi.ocean-insights.com/containertracking/v2/subscriptions/110015398/",
                "tags": [],
                "tsp1_vslarrival_prediction": null,
                "tsp2_vslarrival_prediction": null,
                "tsp3_vslarrival_prediction": null,
                "tsp4_vslarrival_prediction": null,
                "pod_vslarrival_prediction": null,
                "pod_discharge_prediction": null,
                "leg1_service": null,
                "leg2_service": null,
                "leg3_service": null,
                "leg4_service": null,
                "leg5_service": null,
                "pod_timeofarrival_warning": null,
                "empty_pickup_loc": null,
                "availability_loc": null,
                "lif_loc": null,
                "empty_return_loc": null,
                "incidents": [],
                "identifiers": [
                    {
                        "type": "b_id",
                        "reference_number": "721037207"
                    }
                ],
                "booking_number": null,
                "bl_number": "MAEU721037207",
                "weight": null,
                "status": 19,
                "lifecycle_status": 0,
                "id_date": "2025-09-15",
                "empty_pickup_planned_initial": null,
                "empty_pickup_planned_last": null,
                "empty_pickup_actual": null,
                "origin_pickup_planned_initial": null,
                "origin_pickup_planned_last": null,
                "origin_pickup_actual": null,
                "pol_arrival_planned_initial": null,
                "pol_arrival_planned_last": null,
                "pol_arrival_actual": "2025-09-15T17:32+0000",
                "pol_loaded_planned_initial": null,
                "pol_loaded_planned_last": null,
                "pol_loaded_actual": "2025-09-19T13:51+0000",
                "pol_vsldeparture_planned_initial": null,
                "pol_vsldeparture_planned_last": null,
                "pol_vsldeparture_actual": "2025-09-19T20:06+0000",
                "pol_vsldeparture_detected": "2025-09-19T20:20+0000",
                "leg1_voyage": "537S",
                "tsp1_vslarrival_planned_initial": null,
                "tsp1_vslarrival_planned_last": null,
                "tsp1_vslarrival_actual": null,
                "tsp1_vslarrival_detected": null,
                "tsp1_discharge_planned_initial": null,
                "tsp1_discharge_planned_last": null,
                "tsp1_discharge_actual": null,
                "tsp1_loaded_planned_initial": null,
                "tsp1_loaded_planned_last": null,
                "tsp1_loaded_actual": null,
                "tsp1_vsldeparture_planned_initial": null,
                "tsp1_vsldeparture_planned_last": null,
                "tsp1_vsldeparture_actual": null,
                "tsp1_vsldeparture_detected": null,
                "leg2_voyage": null,
                "tsp2_vslarrival_planned_initial": null,
                "tsp2_vslarrival_planned_last": null,
                "tsp2_vslarrival_actual": null,
                "tsp2_vslarrival_detected": null,
                "tsp2_discharge_planned_initial": null,
                "tsp2_discharge_planned_last": null,
                "tsp2_discharge_actual": null,
                "tsp2_loaded_planned_initial": null,
                "tsp2_loaded_planned_last": null,
                "tsp2_loaded_actual": null,
                "tsp2_vsldeparture_planned_initial": null,
                "tsp2_vsldeparture_planned_last": null,
                "tsp2_vsldeparture_actual": null,
                "tsp2_vsldeparture_detected": null,
                "leg3_voyage": null,
                "tsp3_vslarrival_planned_initial": null,
                "tsp3_vslarrival_planned_last": null,
                "tsp3_vslarrival_actual": null,
                "tsp3_vslarrival_detected": null,
                "tsp3_discharge_planned_initial": null,
                "tsp3_discharge_planned_last": null,
                "tsp3_discharge_actual": null,
                "tsp3_loaded_planned_initial": null,
                "tsp3_loaded_planned_last": null,
                "tsp3_loaded_actual": null,
                "tsp3_vsldeparture_planned_initial": null,
                "tsp3_vsldeparture_planned_last": null,
                "tsp3_vsldeparture_actual": null,
                "tsp3_vsldeparture_detected": null,
                "leg4_voyage": null,
                "tsp4_vslarrival_planned_initial": null,
                "tsp4_vslarrival_planned_last": null,
                "tsp4_vslarrival_actual": null,
                "tsp4_vslarrival_detected": null,
                "tsp4_discharge_planned_initial": null,
                "tsp4_discharge_planned_last": null,
                "tsp4_discharge_actual": null,
                "tsp4_loaded_planned_initial": null,
                "tsp4_loaded_planned_last": null,
                "tsp4_loaded_actual": null,
                "tsp4_vsldeparture_planned_initial": null,
                "tsp4_vsldeparture_planned_last": null,
                "tsp4_vsldeparture_actual": null,
                "tsp4_vsldeparture_detected": null,
                "leg5_voyage": null,
                "pod_vslarrival_planned_initial": null,
                "pod_vslarrival_planned_last": null,
                "pod_vslarrival_actual": "2025-09-27T18:39+0000",
                "pod_vslarrival_detected": "2025-09-27T18:23+0000",
                "pod_discharge_planned_initial": null,
                "pod_discharge_planned_last": null,
                "pod_discharge_actual": "2025-09-28T10:08+0000",
                "pod_departure_planned_initial": null,
                "pod_departure_planned_last": null,
                "pod_departure_actual": "2025-10-02T07:51+0000",
                "lif_arrival_planned_initial": null,
                "lif_arrival_planned_last": null,
                "lif_arrival_actual": null,
                "lif_departure_planned_initial": null,
                "lif_departure_planned_last": null,
                "lif_departure_actual": null,
                "dlv_delivery_planned_initial": null,
                "dlv_delivery_planned_last": null,
                "dlv_delivery_actual": null,
                "empty_return_planned_initial": null,
                "empty_return_planned_last": null,
                "empty_return_actual": null,
                "empty_return_customer": null,
                "ts_count": 0,
                "customs_release_state": null,
                "customs_release_date": null,
                "carrier_release_state": null,
                "carrier_release_date": null,
                "availability_date": null,
                "created": "2025-10-01T11:47+0000",
                "modified": "2025-10-16T02:34+0000",
                "shipment_status_page_url": "https://ctt.ocean-insights.com/#/shipment/69879368?share=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImQzNzQ3M2FkMWY4YzRjZTg5NDM5YTFkZTVmZTE4Y2U2In0.eyJzdWIiOiJzaHA6Njk4NzkzNjgiLCJub25jZSI6Ink5dXJBdmNSaDFnRlpVSnlLMV9mOFNkSF83TTUxUm4xcFgxdlRrZVkyTmsifQ.g5gWp6Cr3dDmoAnNcmI2FE_McZo6okacMSloj9a5zpo"
            },
            {
                "id": 69879369,
                "shipmentsubscription_status": 1,
                "status_verbose": "land transport to Place of Delivery",
                "current_vessel_nextport": null,
                "current_vessel_position": null,
                "current_vessel": null,
                "container_type_iso": "22TN",
                "container_type_str": "20 ft Standard Tank Container",
                "shipmentsubscription_status_verbose": "active",
                "shipmentsubscription_on_hold": false,
                "shipmentsubscription_id": 110015398,
                "lifecycle_status_verbose": "active",
                "tsp4_loc": null,
                "tsp3_loc": null,
                "tsp2_loc": null,
                "tsp1_loc": null,
                "leg5_vessel": null,
                "leg4_vessel": null,
                "leg3_vessel": null,
                "leg2_vessel": null,
                "leg1_vessel": {
                    "name": "VAGA MAERSK",
                    "imo": 9778545,
                    "id": 7457146
                },
                "dlv_loc": null,
                "pod_loc": {
                    "name": "Alexandria (Al Iskandariyh)",
                    "locode": "EGALY",
                    "timezone": "Africa/Cairo",
                    "latitude": 31.166667,
                    "longitude": 29.833333,
                    "city": "Alexandria",
                    "state": "Alexandria",
                    "country": "Egypt",
                    "country_iso2": "EG",
                    "country_iso3": "EGY"
                },
                "pol_loc": {
                    "name": "Antwerp",
                    "locode": "BEANR",
                    "timezone": "Europe/Brussels",
                    "latitude": 51.216667,
                    "longitude": 4.4,
                    "city": "Antwerpen",
                    "state": "Flanders",
                    "country": "Belgium",
                    "country_iso2": "BE",
                    "country_iso3": "BEL"
                },
                "origin_loc": null,
                "carrier_name": "Maersk",
                "carrier_scac": "MAEU",
                "container_number": "SEGU8165325",
                "descriptive_name": null,
                "shipmentsubscription_descriptive_name": null,
                "shipmentsubscription_tags": [],
                "transport_modes_verbose": [
                    "ocean"
                ],
                "transport_modes": [
                    10
                ],
                "url": "https://capi.ocean-insights.com/containertracking/v2/shipments/69879369/",
                "shipmentsubscription": "https://capi.ocean-insights.com/containertracking/v2/subscriptions/110015398/",
                "tags": [],
                "tsp1_vslarrival_prediction": null,
                "tsp2_vslarrival_prediction": null,
                "tsp3_vslarrival_prediction": null,
                "tsp4_vslarrival_prediction": null,
                "pod_vslarrival_prediction": null,
                "pod_discharge_prediction": null,
                "leg1_service": null,
                "leg2_service": null,
                "leg3_service": null,
                "leg4_service": null,
                "leg5_service": null,
                "pod_timeofarrival_warning": null,
                "empty_pickup_loc": null,
                "availability_loc": null,
                "lif_loc": null,
                "empty_return_loc": null,
                "incidents": [],
                "identifiers": [
                    {
                        "type": "b_id",
                        "reference_number": "721037207"
                    }
                ],
                "booking_number": null,
                "bl_number": "MAEU721037207",
                "weight": null,
                "status": 19,
                "lifecycle_status": 0,
                "id_date": "2025-09-16",
                "empty_pickup_planned_initial": null,
                "empty_pickup_planned_last": null,
                "empty_pickup_actual": null,
                "origin_pickup_planned_initial": null,
                "origin_pickup_planned_last": null,
                "origin_pickup_actual": null,
                "pol_arrival_planned_initial": null,
                "pol_arrival_planned_last": null,
                "pol_arrival_actual": "2025-09-16T04:36+0000",
                "pol_loaded_planned_initial": null,
                "pol_loaded_planned_last": null,
                "pol_loaded_actual": "2025-09-19T14:06+0000",
                "pol_vsldeparture_planned_initial": null,
                "pol_vsldeparture_planned_last": null,
                "pol_vsldeparture_actual": "2025-09-19T20:06+0000",
                "pol_vsldeparture_detected": "2025-09-19T20:20+0000",
                "leg1_voyage": "537S",
                "tsp1_vslarrival_planned_initial": null,
                "tsp1_vslarrival_planned_last": null,
                "tsp1_vslarrival_actual": null,
                "tsp1_vslarrival_detected": null,
                "tsp1_discharge_planned_initial": null,
                "tsp1_discharge_planned_last": null,
                "tsp1_discharge_actual": null,
                "tsp1_loaded_planned_initial": null,
                "tsp1_loaded_planned_last": null,
                "tsp1_loaded_actual": null,
                "tsp1_vsldeparture_planned_initial": null,
                "tsp1_vsldeparture_planned_last": null,
                "tsp1_vsldeparture_actual": null,
                "tsp1_vsldeparture_detected": null,
                "leg2_voyage": null,
                "tsp2_vslarrival_planned_initial": null,
                "tsp2_vslarrival_planned_last": null,
                "tsp2_vslarrival_actual": null,
                "tsp2_vslarrival_detected": null,
                "tsp2_discharge_planned_initial": null,
                "tsp2_discharge_planned_last": null,
                "tsp2_discharge_actual": null,
                "tsp2_loaded_planned_initial": null,
                "tsp2_loaded_planned_last": null,
                "tsp2_loaded_actual": null,
                "tsp2_vsldeparture_planned_initial": null,
                "tsp2_vsldeparture_planned_last": null,
                "tsp2_vsldeparture_actual": null,
                "tsp2_vsldeparture_detected": null,
                "leg3_voyage": null,
                "tsp3_vslarrival_planned_initial": null,
                "tsp3_vslarrival_planned_last": null,
                "tsp3_vslarrival_actual": null,
                "tsp3_vslarrival_detected": null,
                "tsp3_discharge_planned_initial": null,
                "tsp3_discharge_planned_last": null,
                "tsp3_discharge_actual": null,
                "tsp3_loaded_planned_initial": null,
                "tsp3_loaded_planned_last": null,
                "tsp3_loaded_actual": null,
                "tsp3_vsldeparture_planned_initial": null,
                "tsp3_vsldeparture_planned_last": null,
                "tsp3_vsldeparture_actual": null,
                "tsp3_vsldeparture_detected": null,
                "leg4_voyage": null,
                "tsp4_vslarrival_planned_initial": null,
                "tsp4_vslarrival_planned_last": null,
                "tsp4_vslarrival_actual": null,
                "tsp4_vslarrival_detected": null,
                "tsp4_discharge_planned_initial": null,
                "tsp4_discharge_planned_last": null,
                "tsp4_discharge_actual": null,
                "tsp4_loaded_planned_initial": null,
                "tsp4_loaded_planned_last": null,
                "tsp4_loaded_actual": null,
                "tsp4_vsldeparture_planned_initial": null,
                "tsp4_vsldeparture_planned_last": null,
                "tsp4_vsldeparture_actual": null,
                "tsp4_vsldeparture_detected": null,
                "leg5_voyage": null,
                "pod_vslarrival_planned_initial": null,
                "pod_vslarrival_planned_last": null,
                "pod_vslarrival_actual": "2025-09-27T18:39+0000",
                "pod_vslarrival_detected": "2025-09-27T18:23+0000",
                "pod_discharge_planned_initial": null,
                "pod_discharge_planned_last": null,
                "pod_discharge_actual": "2025-09-28T09:57+0000",
                "pod_departure_planned_initial": null,
                "pod_departure_planned_last": null,
                "pod_departure_actual": "2025-10-02T10:44+0000",
                "lif_arrival_planned_initial": null,
                "lif_arrival_planned_last": null,
                "lif_arrival_actual": null,
                "lif_departure_planned_initial": null,
                "lif_departure_planned_last": null,
                "lif_departure_actual": null,
                "dlv_delivery_planned_initial": null,
                "dlv_delivery_planned_last": null,
                "dlv_delivery_actual": null,
                "empty_return_planned_initial": null,
                "empty_return_planned_last": null,
                "empty_return_actual": null,
                "empty_return_customer": null,
                "ts_count": 0,
                "customs_release_state": null,
                "customs_release_date": null,
                "carrier_release_state": null,
                "carrier_release_date": null,
                "availability_date": null,
                "created": "2025-10-01T11:47+0000",
                "modified": "2025-10-16T02:34+0000",
                "shipment_status_page_url": "https://ctt.ocean-insights.com/#/shipment/69879369?share=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImQzNzQ3M2FkMWY4YzRjZTg5NDM5YTFkZTVmZTE4Y2U2In0.eyJzdWIiOiJzaHA6Njk4NzkzNjkiLCJub25jZSI6Ik5WN0ZQazkzekIwLUdBNmxaM0pFbXlNY2xJRGlqQjNxWnhOWlgxQUItWXcifQ.wx8pV8p6SOoLn2HlReXKYFzHn1pY39To801fiIBk5Ao"
            },
            {
                "id": 69879370,
                "shipmentsubscription_status": 1,
                "status_verbose": "land transport to Place of Delivery",
                "current_vessel_nextport": null,
                "current_vessel_position": null,
                "current_vessel": null,
                "container_type_iso": "22TN",
                "container_type_str": "20 ft Standard Tank Container",
                "shipmentsubscription_status_verbose": "active",
                "shipmentsubscription_on_hold": false,
                "shipmentsubscription_id": 110015398,
                "lifecycle_status_verbose": "active",
                "tsp4_loc": null,
                "tsp3_loc": null,
                "tsp2_loc": null,
                "tsp1_loc": null,
                "leg5_vessel": null,
                "leg4_vessel": null,
                "leg3_vessel": null,
                "leg2_vessel": null,
                "leg1_vessel": {
                    "name": "VAGA MAERSK",
                    "imo": 9778545,
                    "id": 7457146
                },
                "dlv_loc": null,
                "pod_loc": {
                    "name": "Alexandria (Al Iskandariyh)",
                    "locode": "EGALY",
                    "timezone": "Africa/Cairo",
                    "latitude": 31.166667,
                    "longitude": 29.833333,
                    "city": "Alexandria",
                    "state": "Alexandria",
                    "country": "Egypt",
                    "country_iso2": "EG",
                    "country_iso3": "EGY"
                },
                "pol_loc": {
                    "name": "Antwerp",
                    "locode": "BEANR",
                    "timezone": "Europe/Brussels",
                    "latitude": 51.216667,
                    "longitude": 4.4,
                    "city": "Antwerpen",
                    "state": "Flanders",
                    "country": "Belgium",
                    "country_iso2": "BE",
                    "country_iso3": "BEL"
                },
                "origin_loc": null,
                "carrier_name": "Maersk",
                "carrier_scac": "MAEU",
                "container_number": "GMCU3051340",
                "descriptive_name": null,
                "shipmentsubscription_descriptive_name": null,
                "shipmentsubscription_tags": [],
                "transport_modes_verbose": [
                    "ocean"
                ],
                "transport_modes": [
                    10
                ],
                "url": "https://capi.ocean-insights.com/containertracking/v2/shipments/69879370/",
                "shipmentsubscription": "https://capi.ocean-insights.com/containertracking/v2/subscriptions/110015398/",
                "tags": [],
                "tsp1_vslarrival_prediction": null,
                "tsp2_vslarrival_prediction": null,
                "tsp3_vslarrival_prediction": null,
                "tsp4_vslarrival_prediction": null,
                "pod_vslarrival_prediction": null,
                "pod_discharge_prediction": null,
                "leg1_service": null,
                "leg2_service": null,
                "leg3_service": null,
                "leg4_service": null,
                "leg5_service": null,
                "pod_timeofarrival_warning": null,
                "empty_pickup_loc": null,
                "availability_loc": null,
                "lif_loc": null,
                "empty_return_loc": null,
                "incidents": [],
                "identifiers": [
                    {
                        "type": "b_id",
                        "reference_number": "721037207"
                    }
                ],
                "booking_number": null,
                "bl_number": "MAEU721037207",
                "weight": null,
                "status": 19,
                "lifecycle_status": 0,
                "id_date": "2025-09-16",
                "empty_pickup_planned_initial": null,
                "empty_pickup_planned_last": null,
                "empty_pickup_actual": null,
                "origin_pickup_planned_initial": null,
                "origin_pickup_planned_last": null,
                "origin_pickup_actual": null,
                "pol_arrival_planned_initial": null,
                "pol_arrival_planned_last": null,
                "pol_arrival_actual": "2025-09-16T04:55+0000",
                "pol_loaded_planned_initial": null,
                "pol_loaded_planned_last": null,
                "pol_loaded_actual": "2025-09-19T13:51+0000",
                "pol_vsldeparture_planned_initial": null,
                "pol_vsldeparture_planned_last": null,
                "pol_vsldeparture_actual": "2025-09-19T20:06+0000",
                "pol_vsldeparture_detected": "2025-09-19T20:20+0000",
                "leg1_voyage": "537S",
                "tsp1_vslarrival_planned_initial": null,
                "tsp1_vslarrival_planned_last": null,
                "tsp1_vslarrival_actual": null,
                "tsp1_vslarrival_detected": null,
                "tsp1_discharge_planned_initial": null,
                "tsp1_discharge_planned_last": null,
                "tsp1_discharge_actual": null,
                "tsp1_loaded_planned_initial": null,
                "tsp1_loaded_planned_last": null,
                "tsp1_loaded_actual": null,
                "tsp1_vsldeparture_planned_initial": null,
                "tsp1_vsldeparture_planned_last": null,
                "tsp1_vsldeparture_actual": null,
                "tsp1_vsldeparture_detected": null,
                "leg2_voyage": null,
                "tsp2_vslarrival_planned_initial": null,
                "tsp2_vslarrival_planned_last": null,
                "tsp2_vslarrival_actual": null,
                "tsp2_vslarrival_detected": null,
                "tsp2_discharge_planned_initial": null,
                "tsp2_discharge_planned_last": null,
                "tsp2_discharge_actual": null,
                "tsp2_loaded_planned_initial": null,
                "tsp2_loaded_planned_last": null,
                "tsp2_loaded_actual": null,
                "tsp2_vsldeparture_planned_initial": null,
                "tsp2_vsldeparture_planned_last": null,
                "tsp2_vsldeparture_actual": null,
                "tsp2_vsldeparture_detected": null,
                "leg3_voyage": null,
                "tsp3_vslarrival_planned_initial": null,
                "tsp3_vslarrival_planned_last": null,
                "tsp3_vslarrival_actual": null,
                "tsp3_vslarrival_detected": null,
                "tsp3_discharge_planned_initial": null,
                "tsp3_discharge_planned_last": null,
                "tsp3_discharge_actual": null,
                "tsp3_loaded_planned_initial": null,
                "tsp3_loaded_planned_last": null,
                "tsp3_loaded_actual": null,
                "tsp3_vsldeparture_planned_initial": null,
                "tsp3_vsldeparture_planned_last": null,
                "tsp3_vsldeparture_actual": null,
                "tsp3_vsldeparture_detected": null,
                "leg4_voyage": null,
                "tsp4_vslarrival_planned_initial": null,
                "tsp4_vslarrival_planned_last": null,
                "tsp4_vslarrival_actual": null,
                "tsp4_vslarrival_detected": null,
                "tsp4_discharge_planned_initial": null,
                "tsp4_discharge_planned_last": null,
                "tsp4_discharge_actual": null,
                "tsp4_loaded_planned_initial": null,
                "tsp4_loaded_planned_last": null,
                "tsp4_loaded_actual": null,
                "tsp4_vsldeparture_planned_initial": null,
                "tsp4_vsldeparture_planned_last": null,
                "tsp4_vsldeparture_actual": null,
                "tsp4_vsldeparture_detected": null,
                "leg5_voyage": null,
                "pod_vslarrival_planned_initial": null,
                "pod_vslarrival_planned_last": null,
                "pod_vslarrival_actual": "2025-09-27T18:39+0000",
                "pod_vslarrival_detected": "2025-09-27T18:23+0000",
                "pod_discharge_planned_initial": null,
                "pod_discharge_planned_last": null,
                "pod_discharge_actual": "2025-09-28T10:06+0000",
                "pod_departure_planned_initial": null,
                "pod_departure_planned_last": null,
                "pod_departure_actual": "2025-10-02T07:51+0000",
                "lif_arrival_planned_initial": null,
                "lif_arrival_planned_last": null,
                "lif_arrival_actual": null,
                "lif_departure_planned_initial": null,
                "lif_departure_planned_last": null,
                "lif_departure_actual": null,
                "dlv_delivery_planned_initial": null,
                "dlv_delivery_planned_last": null,
                "dlv_delivery_actual": null,
                "empty_return_planned_initial": null,
                "empty_return_planned_last": null,
                "empty_return_actual": null,
                "empty_return_customer": null,
                "ts_count": 0,
                "customs_release_state": null,
                "customs_release_date": null,
                "carrier_release_state": null,
                "carrier_release_date": null,
                "availability_date": null,
                "created": "2025-10-01T11:47+0000",
                "modified": "2025-10-16T02:34+0000",
                "shipment_status_page_url": "https://ctt.ocean-insights.com/#/shipment/69879370?share=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImQzNzQ3M2FkMWY4YzRjZTg5NDM5YTFkZTVmZTE4Y2U2In0.eyJzdWIiOiJzaHA6Njk4NzkzNzAiLCJub25jZSI6IkEwOVpBaHVUb2hUMEdKWFhqblRPUXAyNFFPc3drNVo3RElKWmpGMEhBaWMifQ.DXTMDNiNhIEDcmRmNKfkPsGPk0RW4wrRy1AjBzgdawA"
            }
        ],
        "subscription_status_page_url": "https://ctt.ocean-insights.com/#/subscription/110015398?share=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImQzNzQ3M2FkMWY4YzRjZTg5NDM5YTFkZTVmZTE4Y2U2In0.eyJzdWIiOiJzdWI6MTEwMDE1Mzk4Iiwibm9uY2UiOiJzdm9PcVY2eTZFaThnRGNEWG1BVzVaVjlwQkhhT3prdVFZQ2doZ3Jka2FnIn0.aSK7tKQv151H78eJwVCJ_rMTQgbkZ1U66qNoBR7WReY"
    }
]
'''

def reqKey = "MAEU721037207"
def accId = 4913

// body = '{ "root": ' + body + '}'
def jsonSlurper = new JsonSlurper()
def jsonArr = jsonSlurper.parseText(jsonData)

def ids = []
jsonArr.find { obj ->
    if (obj.containsKey("request_key") && obj.containsKey("request_type") && obj.containsKey("status_verbose") && obj.containsKey("account_id")) {
        if (obj.request_key.equals(reqKey) && obj.request_type.equals("m_bl") && obj.account_id == accId && (obj.status_verbose.equals("active") || obj.status_verbose.equals("new"))) {
            ids.add(obj.id)
        }
        // println(obj.request_key)
        // println(obj.request_type)
        // println(obj.account_id)
        // println(obj.status_verbose)
        // println("==================")
    }
}

def result = ids.join(",")
print(result)
